### ISSUE TITLE
Add compatibility with iOS 10

### ISSUE THREAD

**Issue by gil--** [bendrucker/sms-link#2]
It appears Apple changed the SMS protocol yet again in iOS so this will no longer work for Safari 10 devices.

I don't yet have an iOS 10 device to test for new working sms protocol but testing on another person's device I noticed this no longer works for the upcoming iOS 10.

**Comment by bendrucker** [comment]
Good catch, thanks! I'll have an iOS 10 device on Friday. It's kind of weird to test these because the simulator doesn't have a Messages app and won't handle the links even if they're valid. I'll see if I can dig up anything and send it along to friends on the beta.

**Comment by bendrucker** [comment]
FWIW, Apple has said the following for a while:

> The URL string must not include any message text or other information.

But of course it worked anyway 😉

**Comment by gil--** [comment]
https://github.com/bendrucker/ios-version/pull/1 should resolve this by adding double digit ios major version support to the regex.

**Comment by bendrucker** [comment]
Resolved by bendrucker/ios-version#1
