### ISSUE TITLE
Message content after  '&'  disappear

### ISSUE THREAD

**Issue by yoyodream2017** [bendrucker/sms-link#4]
I checked link url and find the `&`  character has been encoded as `%26`. But if I click the link on mobile, the message content after `&` will still disappear. Could you help to find a solution?
Android version: 7.0

**Comment by bendrucker** [comment]
> Could you help to find a solution?

No, I'll need you to contribute here. I don't have an Android device and since this library is using an unofficial protocol I rely on users to research and test on devices they want to support.

I'd be happy to help with a PR or continue discussion if you want to work on this.
